#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/oneplus2

PRODUCT_COPY_FILES += \
    vendor/oneplus/oneplus2/proprietary/system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/oneplus/oneplus2/proprietary/system/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/oneplus/oneplus2/proprietary/system/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/oneplus/oneplus2/proprietary/system/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/oneplus/oneplus2/proprietary/system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/oneplus/oneplus2/proprietary/system/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/oneplus/oneplus2/proprietary/system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/oneplus/oneplus2/proprietary/system/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/data/dsi_config.xml \
    vendor/oneplus/oneplus2/proprietary/system/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/data/netmgr_config.xml \
    vendor/oneplus/oneplus2/proprietary/system/etc/data/qmi_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/data/qmi_config.xml \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/a420_pfp.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/a420_pfp.fw \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/a420_pm4.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/a420_pm4.fw \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/cpp_firmware_v1_8_0.fw \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/fingerprints.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fingerprints.b00 \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/fingerprints.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fingerprints.b01 \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/fingerprints.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fingerprints.b02 \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/fingerprints.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fingerprints.b03 \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/fingerprints.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/fingerprints.mdt \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/mbn_ota/mcfg_sw_ATT-VoLTE.mbn:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mbn_ota/mcfg_sw_ATT-VoLTE.mbn \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/mbn_ota/mcfg_sw_CMCC_CSFB_DSDS_Commercial_Volte.mbn:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mbn_ota/mcfg_sw_CMCC_CSFB_DSDS_Commercial_Volte.mbn \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/mbn_ota/mcfg_sw_CU_OpenMkt-Commercial.mbn:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mbn_ota/mcfg_sw_CU_OpenMkt-Commercial.mbn \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/mbn_ota/mcfg_sw_OEM_Overseas-Commercial.mbn:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mbn_ota/mcfg_sw_OEM_Overseas-Commercial.mbn \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/mbn_ota/mcfg_sw_Reliance-Commercial.mbn:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mbn_ota/mcfg_sw_Reliance-Commercial.mbn \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/mbn_ota/mcfg_sw_TMO-Commercial.mbn:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/mbn_ota/mcfg_sw_TMO-Commercial.mbn \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tfa98xx.cnt \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/tp/14049/14049_FW_S1302.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tp/14049/14049_FW_S1302.img \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/tp/14049/14049_FW_S3320_jdi.img:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/tp/14049/14049_FW_S3320_jdi.img \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/venus.b00:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/venus.b00 \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/venus.b01:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/venus.b01 \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/venus.b02:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/venus.b02 \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/venus.b03:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/venus.b03 \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/venus.b04:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/venus.b04 \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/venus.mbn:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/venus.mbn \
    vendor/oneplus/oneplus2/proprietary/system/etc/firmware/venus.mdt:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/venus.mdt \
    vendor/oneplus/oneplus2/proprietary/system/etc/permissions/imscm.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/imscm.xml \
    vendor/oneplus/oneplus2/proprietary/system/etc/permissions/qcnvitems.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qcnvitems.xml \
    vendor/oneplus/oneplus2/proprietary/system/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qcrilhook.xml \
    vendor/oneplus/oneplus2/proprietary/system/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qti_libpermissions.xml \
    vendor/oneplus/oneplus2/proprietary/system/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qti_permissions.xml \
    vendor/oneplus/oneplus2/proprietary/system/etc/permissions/telephonyservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/telephonyservice.xml \
    vendor/oneplus/oneplus2/proprietary/system/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/oneplus/oneplus2/proprietary/system/etc/thermal-engine.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/thermal-engine.conf \
    vendor/oneplus/oneplus2/proprietary/vendor/etc/perf-profile0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile0.conf \
    vendor/oneplus/oneplus2/proprietary/vendor/etc/perf-profile1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile1.conf \
    vendor/oneplus/oneplus2/proprietary/vendor/etc/perf-profile2.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile2.conf \
    vendor/oneplus/oneplus2/proprietary/vendor/etc/perf-profile3.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile3.conf \
    vendor/oneplus/oneplus2/proprietary/vendor/etc/perf-profile4.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile4.conf \
    vendor/oneplus/oneplus2/proprietary/vendor/etc/perf-profile5.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile5.conf \
    vendor/oneplus/oneplus2/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/oneplus/oneplus2/proprietary/vendor/firmware/nvm_tlv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvm_tlv.bin \
    vendor/oneplus/oneplus2/proprietary/vendor/firmware/nvm_tlv_1.3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvm_tlv_1.3.bin \
    vendor/oneplus/oneplus2/proprietary/vendor/firmware/nvm_tlv_2.1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvm_tlv_2.1.bin \
    vendor/oneplus/oneplus2/proprietary/vendor/firmware/nvm_tlv_3.0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvm_tlv_3.0.bin \
    vendor/oneplus/oneplus2/proprietary/vendor/firmware/nvm_tlv_3.2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nvm_tlv_3.2.bin \
    vendor/oneplus/oneplus2/proprietary/vendor/firmware/rampatch_tlv.img:$(TARGET_COPY_OUT_VENDOR)/firmware/rampatch_tlv.img \
    vendor/oneplus/oneplus2/proprietary/vendor/firmware/rampatch_tlv_1.3.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/rampatch_tlv_1.3.tlv \
    vendor/oneplus/oneplus2/proprietary/vendor/firmware/rampatch_tlv_2.1.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/rampatch_tlv_2.1.tlv \
    vendor/oneplus/oneplus2/proprietary/vendor/firmware/rampatch_tlv_3.0.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/rampatch_tlv_3.0.tlv \
    vendor/oneplus/oneplus2/proprietary/vendor/firmware/rampatch_tlv_3.2.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/rampatch_tlv_3.2.tlv \
    vendor/oneplus/oneplus2/proprietary/vendor/qcril.db:$(TARGET_COPY_OUT_VENDOR)/qcril.db

PRODUCT_PACKAGES += \
    fingerprint.msm8994 \
    lib_fpc_tac_shared \
    libFNVfbEngineLib \
    libmm-qcamera \
    libmorpho_video_refiner \
    libopcamerahw_interface \
    libloc_api_v02 \
    libloc_ds_api \
    libopcamera \
    libopcameralib \
    libparam \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    libq3dtools_esx \
    gatekeeper.msm8994 \
    libC2D2 \
    libDivxDrm \
    libOmxAacDec \
    libOmxAmrwbplusDec \
    libOmxWmaDec \
    libOpenCL \
    libQSEEComAPI \
    libSHIMDivxDrm \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadreno_utils \
    libadsprpc \
    libaudcal \
    libbtnv \
    libc2d30-a4xx \
    libdiag \
    libdisp-aba \
    libdsi_netctrl \
    libdsutils \
    libgsl \
    libhwdaphal \
    libidl \
    libllvm-glnext \
    libllvm-qgl \
    libmdmdetect \
    libmm-abl-oem \
    libmm-abl \
    libmm-als \
    libmm-disp-apis \
    libmm-qdcm \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_debug \
    libmmcamera2_stats_algorithm \
    libmmosal \
    libqcci_legacy \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_encdec \
    libqmiservices \
    libqti-perfd-client \
    libscale \
    libsensor1 \
    libsensor_reg \
    libsensor_thresh \
    libsensor_user_cal \
    libsmemlog \
    libthermalclient \
    libtime_genoff \
    sensors.ssc \
    vulkan.msm8994 \
    sound_trigger.primary.msm8994 \
    libOmxEvrcDec \
    libOmxQcelp13Dec \
    libactuator_rohm_bu63165gwl \
    libactuator_rohm_bu63165gwl_camcorder \
    libactuator_rohm_bu63165gwl_camera \
    libchromatix_ov13860_common \
    libchromatix_ov13860_cpp_hfr \
    libchromatix_ov13860_cpp_liveshot \
    libchromatix_ov13860_cpp_panorama \
    libchromatix_ov13860_cpp_preview \
    libchromatix_ov13860_cpp_snapshot \
    libchromatix_ov13860_cpp_video \
    libchromatix_ov13860_cpp_zsl \
    libchromatix_ov13860_default_video \
    libchromatix_ov13860_hfr \
    libchromatix_ov13860_liveshot \
    libchromatix_ov13860_panorama \
    libchromatix_ov13860_postproc \
    libchromatix_ov13860_preview \
    libchromatix_ov13860_quarter_size_video \
    libchromatix_ov13860_snapshot \
    libchromatix_ov13860_zsl \
    libchromatix_ov5648_15fps_cpp_liveshot \
    libchromatix_ov5648_15fps_cpp_preview \
    libchromatix_ov5648_15fps_cpp_snapshot \
    libchromatix_ov5648_15fps_cpp_video \
    libchromatix_ov5648_15fps_postproc \
    libchromatix_ov5648_15fps_preview \
    libchromatix_ov5648_15fps_snapshot \
    libchromatix_ov5648_15fps_video \
    libchromatix_ov5648_30fps_cpp_liveshot \
    libchromatix_ov5648_30fps_cpp_preview \
    libchromatix_ov5648_30fps_cpp_snapshot \
    libchromatix_ov5648_30fps_cpp_video \
    libchromatix_ov5648_30fps_postproc \
    libchromatix_ov5648_30fps_preview \
    libchromatix_ov5648_30fps_snapshot \
    libchromatix_ov5648_30fps_video \
    libchromatix_ov5648_common \
    libfastcvadsp_stub \
    libfastcvopt \
    libflash_pmic \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera2_vpe_module \
    libmmcamera2_wnr_module \
    libmmcamera_cac2_lib \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_faceproc \
    libmmcamera_hdr_gb_lib \
    libmmcamera_imglib \
    libmmcamera_isp_abf44 \
    libmmcamera_isp_bcc44 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_scale_stats46 \
    libmmcamera_isp_bf_stats44 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc44 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_clf46 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic44 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic46 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr46 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_isp_wb46 \
    libmmcamera_ov13860 \
    libmmcamera_ov13860_eeprom \
    libmmcamera_ov5648 \
    libmmcamera_ov5648_eeprom \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_vpu_module \
    libmmipl \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    liboemcamera \
    libois_rohm_bu63165gwl \
    libqomx_jpegdec \
    libqomx_jpegenc_pipe \
    libwvdrmengine \
    com.quicinc.cne.api@1.0 \
    com.quicinc.cne.constants@1.0 \
    flp.default \
    keystore.msm8994 \
    lib-dplmedia \
    lib-ims-rcscmjni \
    lib-imsSDP \
    lib-imscamera \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs \
    lib-imsrcscm \
    lib-imsrcscmclient \
    lib-imsrcscmservice \
    lib-imss \
    lib-imsvt \
    lib-imsxml \
    lib-rcsimssjni \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpdaemoninterface \
    lib-rtpsl \
    libcneapiclient \
    libconfigdb \
    libcrypto_keystore \
    libdataitems \
    libdrmfs \
    libdrmtime \
    libflp \
    libgeofence \
    libimscamera_jni \
    libimsmedia_jni \
    libizat_core \
    liblbs_core \
    liblocationservice \
    liblowi_client \
    liblqe \
    libnetmgr \
    libperipheral_client \
    libqcmaputils \
    libqmi_csi \
    librcc \
    libril-qc-qmi-1 \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librpmb \
    libsettings \
    libssd \
    libsystem_health_mon \
    libthermalioctl \
    libulp2 \
    libvoice-svc \
    libxml \
    QtiTelephonyService \
    datastatusnotification \
    qcrilmsgtunnel \
    ims \
    imssettings \
    QtiTelephonyServicelibrary \
    imscmlibrary \
    qcnvitems \
    qcrilhook \
    rcsimssettings \
    adsprpcd \
    btnvtool \
    cnss-daemon \
    energy-awareness \
    hci_qcomm_init \
    imsdatadaemon \
    imsqmidaemon \
    irsc_util \
    mm-pp-daemon \
    mm-qcamera-daemon \
    msm_irqbalance \
    netmgrd \
    perfd \
    pm-proxy \
    pm-service \
    qmuxd \
    qseecomd \
    qti \
    rfs_access \
    rmt_storage \
    sensors.qcom \
    thermal-engine \
    wcnss_filter

PRODUCT_PACKAGES += \
    vendor_app_ims_lib_arm64_libimscamera_jni_so \
    vendor_app_ims_lib_arm64_libimsmedia_jni_so
